services:

  postgres:
    container_name: booksotre_db
    image: postgres:latest
    ports:
      - "5431:5432"
    expose:
      - 5431
    environment:
      - POSTGRES_USER=fastapi
      - POSTGRES_DB=bookstore
      - POSTGRES_PASSWORD=fastapi_admin
      - POSTGRES_PORT=5432
    volumes:
      - postgresvolume:/var/lib/postgres/data

volumes:
  postgresvolume:
    driver: local